import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const monument = localFont({
  src: [
    {
      path: "../assets/fonts/MonumentExtended-Regular.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--monument",
});

const satoshi = localFont({
  src: [
    {
      path: "../assets/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--satoshi",
});

export const metadata: Metadata = {
  title: "Creon Frontend Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${monument.className} ${satoshi.className}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
